### ISSUE TITLE
Add the possibility to search for files in the packages, like a command name 

### ISSUE THREAD

**Issue by mickours** [NixOS/nixos-search#104]
It would interesting to have a page that permits the users to search for a file in the packages. A good example is a program that you need but you only now the executable name that differ from the package name. For example, I was looking for the `readelf` command and I was not able to find it from the Packages search page or the `nix search` tool.  
 
Debian has a good tool for that:
https://www.debian.org/distrib/packages#search_contents
The readelf example:
https://packages.debian.org/search?searchon=contents&keywords=%2Fbin%2Freadelf&mode=path&suite=stable&arch=any

It would be very nice to have a similar page in the Nixos site.

**Comment by MaurolepisDreki** [comment]
I don't think "interesting" is the right word... nobody seems to know which packages supplies "phpize" and "php.h", and the packages they suggest do not exist in the search.  Minding that I only use NixOS because Replit (my IDE) uses NixOS, it seems **vital** to any distribution to be able to locate the appropriate packages supplying the target tools when they exist at all.

**Comment by ysndr** [comment]
With flakes we can already exctract `app` attributes
I have looked into integrating `nix-index` (for nixpkgs at least).
As far as I see it should be quite possible to either speak with hydra directly or (better) integrate `nix-index` and track files in `<drv>/bin`
It's a bigger amendment to nixos-search and not as pressing here as it's available as its own tool in form of `nix-index`

**Comment by fricklerhandwerk** [comment]
Program names are now indexed. Another use case are libraries: https://github.com/NixOS/nixos-search/issues/673
