### ISSUE TITLE
Add flake search feature

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixos-search#125]
To make flakes more discoverable, we could add the ability to search for/in flakes to search.nixos.org. Ideally this would allow users to find packages, NixOS modules/options, etc. provided by flakes. For instance, a search for `services.hydra` should return the Hydra flake.

We could either index the flakes in the global registry, or all flakes on GitHub (e.g. by doing `https://api.github.com/search/repositories?q=/flake.nix`).

For each flake, we can do `nix flake show github:<owner>/<repo>` and dump the result in Elasticsearch. (TODO: add a `--json` flag to `nix flake show` to make this easier. Also, `nix flake show` doesn't show the options provided by NixOS modules yet.)

**Comment by blaggacao** [comment]
> index the flakes in the global registry

As I'm seeing it right now, those are mostly "indirections" with a shared global namespace.

> all flakes on GitHub (e.g. by doing https://api.github.com/search/repositories?q=/flake.nix)

This is far more powerful, but would have to display forks. I'd prefer this since it supports flakes by design to be a more decentralized and distributed thing.

_Maybe_, we might need discoverability of the distinction of a gitflow contributing fork or a functional fork with added / different functionality.
```nix
{
    functionalFork = true;
}
```
But _more probably_ this problem might reveal itself in time without major negative impact.

**Comment by garbas** [comment]
(from #115) currently we are not exporting aliases. when we rewrite the `nix flake show` we need to also consider including aliases.

**Comment by ysndr** [comment]
I am willing and about to start working on this!

**Comment by garbas** [comment]
This is actually done :)
