### ISSUE TITLE
related options should be together

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-search#132]
Options for the same service should be listed together. Currently, they are all over the place.

![Screenshot from 2020-07-10 05-19-40](https://user-images.githubusercontent.com/91113/87112822-1ce1b800-c26d-11ea-9541-5dddea0c3e1d.png)

(see xrdp)

https://search.nixos.org/options?show=services.xrdp.enable&query=rdp&from=15&size=15&channel=unstable

current site don't has that issue

![Screenshot from 2020-07-10 05-23-04](https://user-images.githubusercontent.com/91113/87112953-7c3fc800-c26d-11ea-9537-56328c51478b.png)

https://nixos.org/nixos/options.html#rdp

**Comment by samueldr** [comment]
:+1: this was something that was discussed about in my call with @garbas.

This is a hard problem if we want relevancy.

The quick fix for a release soon is to allow alphabetical ordering as an option.

This is a hard problem because we don't necessarily have the full result set from the server. This means the elasticsearch query *needs* to have the correct ordering. Doing additional processing client-side could work on partial data.

**Comment by garbas** [comment]
I just implemented sorting which should somewhat fix this issue.
Initial plan is to replace existing packages/options search without changing functionality (except for adding the relevance bit).

An idea that is floating was to group options based on their source file, but then how do you find suboptions etc... The whole idea needs to be put to test. I hope to start working on this soon.

For now I'm closing this issue since it is addressed by #133
