### ISSUE TITLE
"font" search results

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-search#134]
When i search for "font", i get much less results (191) than the current search (365).

https://search.nixos.org/packages?query=font&from=45&size=15&sort=relevance&channel=unstable
https://nixos.org/nixos/packages.html?channel=nixpkgs-unstable&query=font

**Comment by samueldr** [comment]
I don't know what the issue is, but maybe it can be figured out with those terms:


For `literacy`:

 * https://nixos.org/nixos/packages.html?channel=nixpkgs-unstable&query=literacy
 * https://search.nixos.org/packages?query=literacy&from=0&size=15&sort=alpha_asc&channel=unstable


For `Unicode-compliant`:

 * https://nixos.org/nixos/packages.html?channel=nixpkgs-unstable&query=Unicode-compliant
 * https://search.nixos.org/packages?query=Unicode-compliant&from=0&size=15&sort=alpha_asc&channel=unstable

Both are a 1-result search for the *andika* font. The package is indexed:

 * https://nixos.org/nixos/packages.html?channel=nixpkgs-unstable&query=andika
 * https://search.nixos.org/packages?show=andika&query=andika&from=0&size=15&sort=alpha_asc&channel=unstable

So it's not simply a question of something missing from the index.

**Comment by samueldr** [comment]
The search results don't return "andika" for one of the test:

For `Unicode-compliant`:

  *  https://nixos.org/nixos/packages.html?channel=nixpkgs-unstable&query=Unicode-compliant
  *  https://search.nixos.org/packages?query=Unicode-compliant&from=0&size=15&sort=alpha_asc&channel=unstable


Going from the results for the single word `compliant`,  it looks like the **long** description might not be used properly? `clightning` is a result for `compliant` in the old search, while not in the new search; which is *too* only found in the long description field.

(It is okay to split this off into a new issue if it's rude to re-open, though strictly speaking, it's part of this issue AFAICT)
