### ISSUE TITLE
Add link to this repo to the page

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-search#138]
"Report issues at https://github.com/NixOS/nixos-search/issues"

I always have to go to https://github.com/NixOS and select it there...

Visitors might not even know it exists.

**Comment by samueldr** [comment]
While not *truly* a blocker, I think that the time investment needed for this issue is so low, compared to the benefits, that it should be done before switching to this search.

**Especially** considering that this allows end-users to know where to send their problems and suggestions, this is pretty much mandatory to have, in my mind.
