### ISSUE TITLE
Search seems to be OR-based now reducing relevancy for multiple terms

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-search#156]
Results are far less relevant with OR-based search:

 * minifier: 32 results
 * css: 535 results
 * css minifier: 559 results

I have to go through all "css" and "minifier" results when I'm searching for what should have been "css AND minifier".

Is that what 91527f1deb18e3f74b6e52c50cadc08b4366e4f2 changed?

**Comment by garbas** [comment]
Yes this is where change was introduced.

I think we are mixing two things here: relevancy and number of results. Just because there is more results it does not make the search less relevant , what is important is what is on the first positions.

When searching for "css minifield" I would expect also to see results that match (in order of importance):
- "css AND minifier"
- "css"
- "minifier"

We might also show in UI which term is not matched on (like in google). Similarly we could use quotes for things we expect to mach in result (as google does it)

I think what is missing in current implementation is to correctly add weights to represent the order correctly (eg. showing results where css and minifier are present).

**Comment by samueldr** [comment]
Sure, relevancy and number of results are different things. But here there is definitely more *completely irrelevant* results than somewhat relevant results.

There is nothing worse, to me, than the patronizing "we omitted this term from your search" from Google. I believe that doing it here is going to cause more teeth gnashing than limiting the search to an actual *AND*.

Note that I'm thinking that synonyms would be fine, if we had a list of them. I'm thinking about results that completely don't match a term.

This is all made worse by the way the relevancy order is not helping here. The "css minifier" results that are both css and minifiers do not float up to the top. The results are actually quite terrible. Which makes me order by package name, which at least helps me filter out in my mind, which in turn means I would have to go through 559 results. It ends up that the better way to find the css minifiers is to (unintuitively) search for minifiers only, and manually check each of the 32 results.

**Comment by samueldr** [comment]
:o "server" would have been an easy target to break the search!

>  `23:28 <zeta_0>` is `jdt-server` a nix pkg? i can't seem to find it: https://search.nixos.org/packages?query=jdt-server&from=0&size=15&sort=relevance&channel=20.03 
> ` 23:30 <zeta_0>` ya, i think the `Search NixOS packages` web search is not working correctly. 

* https://logs.nix.samueldr.com/nixos/2020-08-27#1598570892-1598571015;

Extrapolating from their needs:

 * https://search.nixos.org/packages?query=JDT%20language%20server&from=0&size=15&sort=alpha_asc&channel=20.03

Sorry for the tone, but this kind of result set is pure garbage. Completely irrelevant packages ordered by whatever fragments of relevancy is not useful, and only will end up confusing users.

**Comment by garbas** [comment]
@samueldr  Well the tone definitely wont persuade me to work on this, but examples where things don't work will - which is how you started this issue. I believe you also like to receive helpful issues on which you can improve things.

If you call the result set **completely irrelevant** then please take the time to explain which part this will really help me to test, otherwise this kind of report is nothing I can act upon.

**Comment by garbas** [comment]
Also `jdk-server` is not a nix package (either in unstable or 20.03). There is a jdk eclipse plugin, but that's it.

**Comment by hmaurer** [comment]
I'm interested in working on this. @samueldr what results would you expect when searching for "JDT language server"?

**Comment by hmaurer** [comment]
There are definitely ranking issues, even with single terms. E.g.

![image](https://user-images.githubusercontent.com/541045/91567130-8bbdc200-e93c-11ea-8a1f-f71d87632907.png)

**Comment by samueldr** [comment]
In this particular instance, I guess no result since the **JDT** Language server is, as far as I can tell, not present. Though note that this isn't *my* search, this was a confused user that is not a comfortable Nix and NixOS user.

I'm sorry, @garbas, for the tone, but I've just been hit myself with tons of results where I have to search for the needle in the haystack. The main thing I expect to see is *fewer* results the more precise I make my search, not more.

**Comment by hmaurer** [comment]
@samueldr I think the argument from @garbas is that OR-based search with relevance sorting could give you results that you want, e.g. you might search for "JDT language server" but perhaps the package you are looking for is named "JDT server". Though I agree that showing a long list of irrelevant results is confusing as well. The user might think "perhaps what I am looking for is on page 2, or page 3", and look through pages of irrelevant results. Pretty bad UX.

**Comment by samueldr** [comment]
I agree with the principle, if it was possible for it to pick only the results which have a high confidence level of matching in this situation, but I don't see it as currently working.

I also think it would help if the interface showed clearly that the results match for fewer terms (or synonyms, if and when implemented). Alternatively, if the backend allows doing it in a trivial manner, suggesting alternative searches when there are no results could help too.

A null result set, in my opinion, is a valid result for a search.
