### ISSUE TITLE
Browser compatibility target

### ISSUE THREAD

**Issue by hmaurer** [NixOS/nixos-search#158]
It'd be good to add the targeted browsers to the README. This would let contributors know which CSS/JS features they can use. Since the target audience is devs I assume the target is something like "recent versions of Firefox/Chrome/Safari", but perhaps there are some additional constraints?

**Comment by garbas** [comment]
@hmaurer Really good idea.

For JS we support what Elm supports.
For CSS I would defer the question to @samueldr since he is implementing new design for nixos.org and this design (eventually) is what search.nixos.org will use.

I think recent versions of Firefox/Chrome/Safari/.. is a good asumption.

**Comment by hmaurer** [comment]
@garbas thanks! Is there anywhere I can see that new design? :) (c.f. @samueldr )

**Comment by garbas** [comment]
@hmaurer we discussed it at [marketing meetings](https://www.youtube.com/watch?v=9zZa7HkvMP8&list=PLt4-_lkyRrOOO8CYo5XPx6UI05q8kwhj0) (check meeting `#10` and `#11` ) and @samueldr is leading the implementation here: https://github.com/NixOS/nixos-homepage/pull/506

**Comment by garbas** [comment]
I'm closing the issue here and adding it to the checklist in https://github.com/NixOS/nixos-homepage/pull/506
