### ISSUE TITLE
Add a new tab to search builtins/lib/nixpkgs.lib

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixos-search#160]
Hi,

There's a discussion going on in #nixos-chat about documentation, and specifically function documentation.

I also have found myself feeling a bit lost on the manual pages, despite spending plenty of time there.

It would be great if there was a tab where we could also search/filter through library functions for builtins, nix lib, nixpkgs lib.

cc: @samueldr

**Comment by eyJhb** [comment]
Noting that I thought it would be nice, with something like this - https://sm.alliedmods.net/api/ :)

**Comment by garbas** [comment]
I agree this would be nice and will eventually be sorted out, just not in next few weeks.

As flakes will become a more common thing we will also have to adjust how we search for things. Idea is that flakes will export documentation which we will indexed and then search over. builtins and nixpkgs.lib need to be then documented as any other part of nix ecosystem. Some work towards documenting this already started in `markdown` branch in nix.

I'll be closing this issues since we plan solve this, but only once things are documented first and exposed via flakes.

**Comment by seghers** [comment]
I just came to the same idea, did an issue search and found this issue.
I'm new to nix and had this issue: https://discourse.nixos.org/t/how-to-add-optional-listitem/14701
I knew there would be something, I just didn't know where to find it.
After google/ddg/reddit/..
After looking trough many peoples configs, I decides to look for where the functions were described.
It turned out to be: nixpkgs/lib. 


I hope my newbie insights help. 
I hope I won't have these insights for much longer...

Thanks for nixos-search, it's really useful.
