### ISSUE TITLE
Package and option search require network access now

### ISSUE THREAD

**Issue by ToxicFrog** [NixOS/nixos-search#192]
The old search did a simple substring search client-side, using javascript. This meant the page took longer to load, but once loaded searches were incremental and instantaneous.

The move to remote Elasticsearch has introduced significant regressions (in addition to the quality-of-results issues reported in #187 et al):
- searches are no longer incremental (presumably because that would result in lots of network requests)
- searches are significantly slower (because you have to wait for the network round-trip)
- searches do not function at all if you have no network connection

If nothing else it would be nice to have the old JS implementation as a fallback. (I realize `nix-env` exists, but search.nixos is a nicer UI and as far as I know you can't use `nix-env` to search options, only packages.)

**Comment by Zopieux** [comment]
Apparently the previous version was based on a *subset* (sample) of *popular* options/packages only. Metrics about how much data we're speaking about would be welcome here, otherwise we can't have a good discussion. If we're speaking O(10MB) it should be fine doing in-browser.

An approach similar to https://devdocs.io/offline could be used, where one can opt-in to download the large (?) offline dataset inside "modern" browser storage such as [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API).

**Comment by ToxicFrog** [comment]
The previous package search was incomplete because it excluded broken and unfree packages, but as far as I know that has now been resolved; I've never heard of options being excluded from option search.

**Comment by garbas** [comment]
@ToxicFrog @Zopieux thank you for taking the time and writing all this down.

With the previous search we hit the limit since we couldn't include all of the packages. Please look at the ticket open in nixos-homepage repo that refer to search being limited to only selected packages. 

Going further (think of flakes) this problem will only become bigger.

Also I don't want to implement a ranking in the frontend.

I was thinking of debouncing on the input and sending queries to elasticsearch, I'm just not 100% sure if our instance can handle it, especially once we add more data to it (tutorials, manuals, site, github issues, etc...)

**Comment by ToxicFrog** [comment]
Alright, thank you for the explanation.
