### ISSUE TITLE
showing package/options details scrolls up

### ISSUE THREAD

**Issue by BenediktSeidl** [NixOS/nixos-search#225]
### how to reproduce

* search for system
* click somewhere to remove focus from search input field
* scroll down
* click on next to last element "gnomeExtensions.system-monitor"
* page scrolls up, you can not see the details of said package, you have to scroll down again to see details
* search input field has focus

### expected result

* page scroll is not changed
* package details visible
* focus is not changed

*tested with ff 68.8.0esr, ff 82.0.3, chromium 80.0.3987.162*

**Comment by garbas** [comment]
@BenediktSeidl thank you for taking the time to report the issue in such detail. This must be a regression of the last change we did.

@turboMaCk do you maybe have some spare time to look into this? Otherwise I will look at it next week.

**Comment by turboMaCk** [comment]
@garbas yes can have a look later today and hopefully open PR with fix

**Comment by turboMaCk** [comment]
This happens because of command for focusing the input which I think happens during the call to some `init` function.

I see two ways of of this issue.

a) we can simply prevent this from happening (probably by introducing some special cases and branching).
b) we can redesign types in a way this will become less of a problem.

I'll try to come up with something more concrete.
