### ISSUE TITLE
Options search doesn't work for 20.09

### ISSUE THREAD

**Issue by ivanovsaleksejs** [NixOS/nixos-search#243]
At the moment, options search for 20.09 doesn't find anything. I tried different keywords that definitely exist, like "services" or "hardware" - always get the same. 

_search action returns a valid object with no errors but with zero results:

```json
{
  "took":0,
  "timed_out":false,
  "_shards":{
    "total":1,
    "successful":1,
    "skipped":0,
    "failed":0
  },
  "hits":{
    "total":{
      "value":0,
      "relation":"eq"
    },
    "max_score":null,
    "hits":[]
  }
}
```

Example URL: https://search.nixos.org/options?channel=20.09&from=0&size=30&sort=relevance&query=services

**Comment by garbas** [comment]
I'm not sure what was happening, but a manual push of 20.09 channel fixed it.

**Comment by boxofrox** [comment]
I found a recurrence (2020-12-06 23:44 EST).  Neither 20.03 nor 20.09 return results, but unstable does show results.  Tested with similar keywords as stated by OP.

**Comment by ivanovsaleksejs** [comment]
Can confirm, it doesn't work again.

**Comment by garbas** [comment]
I (again) manually imported those channels. It should be ok for the time being.

It looks like the problem is intermittent, but occurs in `jsonToNix`:
- https://github.com/NixOS/nixos-search/runs/1505101509?check_suite_focus=true
- https://github.com/NixOS/nixos-search/runs/1508000111?check_suite_focus=true

I'll look how can we improve this.
