### ISSUE TITLE
improve usabilty of nixos option search

### ISSUE THREAD

**Issue by tklitschi** [NixOS/nixos-search#272]
The current [NixOS Search](https://search.nixos.org/options) you took a step in the wrong direction. 
The search the used to have a year ago was a really nice experience, now you have to scroll to see every Option making it difficult to search in a wide variety and can´t even copy the option #271. 
This really makes searching for NixOS options a pain.

**Comment by turboMaCk** [comment]
hi @tklitschi 

Can you please clarify what you mean by this point?

> now you have to scroll to see every Option making it difficult to search in a wide variety

**Comment by turboMaCk** [comment]
@tklitschi Thanks for updating the title to be Options specific. I agree that options is at the moment sadly neglected. I belive this is because nixos-search falls under the wings of marketing team efforts which are currently primarily focused on beginner experience and team expects the primary beginner use-case to be nix package manager on other Linux distributions / MacOS. that's being said I'm not a member of marketing team so further clarification has to come from @garbas 

If you have a sec you can have a look at https://github.com/NixOS/nixos-search/pull/275 or test this url https://600eaa161f0dc71a959aa5fb--nixos-search.netlify.app/packages - It includes my proposed improvements to copy/paste UX especially in options.

If you can expand on what you would like to see or don't like to see in Options search specifically please feel free to expand on that. I myself care about Options search experience and would like to look into this more in next several days in terms of opening PRs with minor improvements as well as coming up with issues for long term improvements (eg I would like to have option to filter by namespace).

**Comment by tklitschi** [comment]
I guess the package search makes sense the way it is implemented now but since package and option search are completely different use cases it doesn't make any practical sense to use the same UI besides marketing. 
I really appreciate your effort in #275 and I guess it a step in right direction.

The big problem is, if I want to get for example into the nginx module and want to get an overview off all options the experience looks like this:
![Peek 2021-01-25 13-17](https://user-images.githubusercontent.com/51724453/105705688-d3a73c00-5f10-11eb-8a59-68d6de17709e.gif)

You get a lot of Information, some you don't need. What made the 'old' nixos-search nice to use, was that you just get the name and by that an idea what that option does and if you want to get detailed information, you could click to expand. 
![old-option](https://user-images.githubusercontent.com/91113/87112822-1ce1b800-c26d-11ea-9541-5dddea0c3e1d.png)
It was nice and compact and you could read everything directly.

**Comment by piegamesde** [comment]
Closely related, the UX of the expand mechanism can be improved in many points:

- It's not navigable by keyboard
- The button is a lot smaller and thus harder to hit than before (Fitts' law)
- The button says "Show/Hide package details" even when searching options
- Placing the button onto the separator line is a weird choice. This makes it feel like the button is not related to one search entry, but *between* two. It also isn't 100% clear whether it refers to the item above or below the line.

**Comment by garbas** [comment]
@tklitschi Thank you for expanding on the issue. We're still experimenting on what and how we want to show. For some description is what they want and I suspect for you this is not the case. I will remove the description and lets see how things turn out.

Also what is coming next is applying the design of nixos.org also for search.nixos.org. At the end of implementing and fixing issues with #261 I was being a bit impatient since this was in the works (behind the scene) for quite some time now. Things like "Show/Hide package details" definitely needs to be improved - as was also said in #261 PR. Overall I think the #261 was step in the right direction, but clearly there are things we need to improve.

@piegamesde I would really appreciate if you open a separate issue so we are able to have conversation with one person and not cross post. If you make more issues but each issue about one specific thing you get a :1st_place_medal: :smile:
