### ISSUE TITLE
Missing Link to <package>.nix in search results

### ISSUE THREAD

**Issue by mkgvt** [NixOS/nixos-search#284]
I like the layout of the new search. Clean and modern.

One of the things that I miss from the old search is the link to the package's source nix file. Would you please restore that functionality? Perhaps put a link section below the maintainers and platforms. That makes it much easier to look through the source for a package since it isn't obvious from the package name/attribute where it is in nixpkgs. (And it saves a step having to clone nixpkgs or bring it up in the browser.)

Additional suggestion. Link directly to the default.nix if it is the only Nix file in the package's directory. Otherwise, link to the directory. (Or put two links, one to the default.nix and one to the directory.) This would make it easier to study the packaging files.

**Comment by garbas** [comment]
> I like the layout of the new search. Clean and modern.
> 

Thank you

> One of the things that I miss from the old search is the link to the package's source nix file. Would you please restore that functionality? Perhaps put a link section below the maintainers and platforms. That makes it much easier to look through the source for a package since it isn't obvious from the package name/attribute where it is in nixpkgs. (And it saves a step having to clone nixpkgs or bring it up in the browser.)
> 

There is a link `Source`  which points to the package's source of the nix file. I agree it is not optimal and must be improved. The visual presentation is going to be addressed with #286 and I'll make sure to present it better.

> Additional suggestion. Link directly to the default.nix if it is the only Nix file in the package's directory. Otherwise, link to the directory. (Or put two links, one to the default.nix and one to the directory.) This would make it easier to study the packaging files.

Currently the link used comes from `nix-env` command. I hope at one point we will also import whole nixpkgs into elasticsearch show the source files directly, but until then this is going to have to do. As far as I can tell this will not happen soon, but with more help who knows maybe it can happen sooner :)

Thank you for reporting, I'm closing this issue since UI is going to be fixed in #286 and the rest I don't have any plans to work on for the foreseeable future.
