### ISSUE TITLE
Link to sources are strange for some packages

### ISSUE THREAD

**Issue by Nebucatnetzer** [NixOS/nixos-search#373]
When searched for MPV I noticed that the source link points to a strange place.
I was expecting a link like the one for unwrapped MPV.

Strange source link: https://github.com/NixOS/nixpkgs/blob/nixos-21.05/pkgs/build-support/trivial-builders.nix#L76

MPV unwrapped source link: https://github.com/NixOS/nixpkgs/blob/nixos-21.05/pkgs/applications/video/mpv/default.nix#L221

User rofrol mentioned a similar issue with the gitFull packagein the forum:
https://discourse.nixos.org/t/wrong-link-to-mpv-source/16141/3

**Comment by ysndr** [comment]
The package `mpv` is actually referring to the wrapper (https://github.com/NixOS/nixpkgs/blob/nixos-21.05/pkgs/applications/video/mpv/wrapper.nix) which uses `symlinkJoin` to bundle mpv with its scripts. `symlinkJoin` on the other hand creates a new derivation through `runCommand` (which the source link refers to). We only get the location where the final _derivation_ is defined and due to this indirection going to the `mpv` default derivation is not possible trivial to automize.

**Comment by Nebucatnetzer** [comment]
Makes sense to me, I'm closing this use then.
Thank you for the reply :).
