### ISSUE TITLE
Include master channel

### ISSUE THREAD

**Issue by PAI5REECHO** [NixOS/nixos-search#462]
I love using the web search interface for getting the TLDR regarding the state of packages in different channels. It'd be nice if the `master` channel was included to see what's going on in the bleeding edge

**Comment by ncfavier** [comment]
That seems like more of a developer use case than a user use case. As a developer, it's not hard to search for issues/PRs mentioning the package you're interested in, or just go to the `nixos-unstable` source and change the branch to `master`.

I suspect indexing `master` would cause unnecessary confusion, and it would fill up our Elasticsearch storage space much faster as it would be reindexed every hour instead of every few days.

**Comment by garbas** [comment]
Another blocker against following the master is that we don't know if master is actually evaluatable (if that is even word). That is what hydra.nixos.org is for. We just need to wait for successful evaluation there.
