### ISSUE TITLE
startx display manager does not support autoLogin... :(

### ISSUE THREAD

**Issue by alpha-bit** [NixOS/nixos-search#492]
hi,

In options at "services.xserver.displayManager" branch, when i "startx.enable=true;" and "autologin.enable=true;" ... nothing happens... :(

I expected the startx would be started, and restarted when ever exited.

Also would be nice to have a ...startx.xinitrc option.

**Comment by ncfavier** [comment]
This is the bug tracker for https://search.nixos.org and not the right place to ask general nix or nixpkgs questions.

`startx` is not a real display manager, it's a program that allows you to start X manually from the console. Enabling the option simply turns off the default display manager, so you can log in at the TTY. If you want *that* to happen automatically, have a look at `services.getty.autologinUser`.

**Comment by alpha-bit** [comment]
Please, when suggesting me to go somewhere else, give me a more direct link to where should i ask what ever i may not here.

I'm asking about options not packages, what should i ask here then?

... though is at "displayManager.startx"... o.O?... :), if is to simply have the startx command available, i would install the package where startx is. It would make sense that this option would go well with the "autologin.enable=true", and behave like a restarting-"window manager".

I'm migrating from debian, where i do auto-login only at tty1 and run startx (which then requests the passord) from .bashrc, just like you seam to suggest. But in nixos "services.getty.autologinUser" does login into all tty*, leaving 5 open consoles... i searched for some option like "services.getty.<tty?>.autologinUser", but found none... any suggestion?

**Comment by ncfavier** [comment]
https://search.nixos.org is only a web interface that allows you to search through nixpkgs packages and options. This bug tracker is for reporting issues with the website itself. For issues with nixpkgs (or NixOS, which is a part of nixpkgs), you can open an issue in the [nixpkgs repository](https://github.com/NixOS/nixpkgs/issues).

For *questions* rather than issues, prefer asking on [Matrix](https://matrix.to/#/#nix:nixos.org) or on [Discourse](https://discourse.nixos.org/).

If you're curious about how `displayManager.startx` is implemented, you can search for the option on https://search.nixos.org and click the "Declared in" link to see the source of the module.

**Comment by alpha-bit** [comment]
i'll set my sails to nixpkgs repository.

i prefer avoiding opening new accounts arround.

yes... maybe i even try to implement the solution my self, if easy enough.

& thank you for the clarification and information...  :)
