### ISSUE TITLE
Render `meta.longDescription` from markdown

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nixos-search#525]
The description of some packages contains markdown, which is currently lost in presentation.

![Screenshot 2022-08-29 at 12 32 02](https://user-images.githubusercontent.com/6599296/187181992-70f2b4de-8cee-44fa-8984-ae0dd0e8db9e.png)

Source: https://github.com/NixOS/nixpkgs/blob/nixos-22.05/pkgs/tools/misc/tmux/default.nix#L69

**Comment by ncfavier** [comment]
While I think this is reasonable, I can't find any authority on what the format of `longDescription` is supposed to be (though the convention seems to be MarkDown). I think this should at least go with a PR in nixpkgs to document in the manual that `longDescription` should be MarkDown, to see what people think.

We should also implement markdown rendering for options, following https://github.com/NixOS/nixpkgs/pull/176146. Currently this is not an issue because we delegate the markdown rendering to nixpkgs for nixos options, and flake authors have not started using `mdDoc`/`literalMD` yet, but it will be at some point.

**Comment by deemp** [comment]
Hi, @ncfavier . In our flake [nix-vscode-extensions](https://github.com/nix-community/nix-vscode-extensions), there's `packages.x86_64-linux.vscodiumWithExtensions.meta.longDescription`. However, this description is not rendered on `search.nixos`

![image](https://user-images.githubusercontent.com/48378098/215744768-49b5f8fe-53d4-4630-bc42-12f8ee75b644.png)

How can we have the `longDescription` rendered as `Markdown`?

**Comment by ncfavier** [comment]
https://github.com/NixOS/nixos-search/pull/607

**Comment by deemp** [comment]
Okay, thanks!
