### ISSUE TITLE
flake import fails due to schema mismatch

### ISSUE THREAD

**Issue by ysndr** [NixOS/nixos-search#534]
The flake import currently seems to fail for all flakes with following error

```
 1: While processing flake github:NixOS/hydra
      
      Caused by:
          0: Failed to analyze flake github:NixOS/hydra
          1: [1]: data did not match any variant of untagged enum FlakeEntry at line 1 column 2238
          2: data did not match any variant of untagged enum FlakeEntry at line 1 column 2238
      
```

This is caused by the generated json parsed by the flak-info tool.
Apparently the output of our script has changed which was not reflected in the rust code.

https://github.com/NixOS/nixos-search/runs/8224307255

**Comment by ncfavier** [comment]
It seems like this is due the the markdown transition in nixpkgs: option descriptions may now look like `{"_type":"mdDoc","text":"..."}`, which does not deserialise to `Option<String>`.

This was not supposed to be a problem until flakes started using `lib.mdDoc`, but, since we index `_module.args` for all flakes and that was given a markdown description in https://github.com/NixOS/nixpkgs/commit/e04a09082e33d444c245e1d5859b37ace25f54a9, things break for all flakes.

So, amusingly, https://github.com/NixOS/nixos-search/pull/528 fixes this issue, although that was not intended at all.

The proper fix, of course, is to make `description` an `Option<DocValue>` and implement markdown rendering.

Also we should probably fail the CI job when *no* flakes are successfully imported.
