### ISSUE TITLE
js injection in search interface is not sanitized

### ISSUE THREAD

**Issue by hansw-nlo** [NixOS/nixos-search#551]
Hi all, 

I noticed it is possible to insert blind js injections in the search interface (search.nixos.org). The js itself is not parsed but it might look like the interface is not checking GET (and probably PUT) variables. Might be good to filter any unwanted html, etc...

**Comment by ncfavier** [comment]
Can you clarify what you mean or give an example? Elm is suppose to take care of XSS sanitisation.

**Comment by hansw-nlo** [comment]
Well, I am not sure if the git interface will show it but here it is:

`'';<!--"<script>alert(1);</script>`

The code is passed as a GET parameter and shown in the searchbox interface exactly how I wrote it. If Git does not show it it could be found in the logfiles of the server.

**Comment by ncfavier** [comment]
> and shown in the searchbox interface exactly how I wrote it

I am not sure what the problem is then. You are free to search for any string on search.nixos.org, just like GitHub lets you type any string into a code block and will render it verbatim. There would be a problem if those user-provided strings were then being *interpreted* as code (for example, if the search strings were *injected* into a context that would lead to the `<script>` tag being parsed as part of the DOM), but that does not seem to be the case here?

**Comment by hansw-nlo** [comment]
Well, for me, as a hacker, it would mean I would try/probe everything where parameters are not sanitized. It means the other parameters might altered too in a way where it could mean problems sooner of later.

**Comment by ncfavier** [comment]
Well, you can probe all you want, but this does not constitute a security issue (and I am fairly confident it would be hard to introduce such an issue, due to Elm's XSS sanitisation); I invite you to search for `'';<!--"<script>alert(1);</script>` in the GitHub search box, or on Google, and see that everything is fine.

Closing as no action required.

**Comment by hansw-nlo** [comment]
Well, good to know when someone has no real sense of security!

**Comment by ysndr** [comment]
Im also not sure what this is about
Did you get the js to execute, i.e. get an alert box?
