### ISSUE TITLE
Can't find helm plugins in search.nixos.org

### ISSUE THREAD

**Issue by yajo** [NixOS/nixos-search#560]
Go to https://search.nixos.org/packages?channel=22.05&from=0&size=50&sort=relevance&type=packages&query=helmplugins and see that there are no results. However, there are a bunch of plugins available.

In https://nixos.org/manual/nixpkgs/stable/ there are no docs about how to create a plugin-ed helm.

This works, but there's no way to discover it unless you read the code:

```nix
      overlays.helm = final: prev: {
        kubernetes-helm-wrapped = final.wrapHelm prev.kubernetes-helm {
          plugins = with final.kubernetes-helmPlugins; [
            helm-diff
          ];
        };
      };
```

@moduon MT-1503

**Comment by ncfavier** [comment]
Looks like the tracking issue for kubernetes documentation is https://github.com/NixOS/nixpkgs/issues/39327, maybe you can chime in there.

Which package sets are displayed in nixos-search is also decided in nixpkgs by the [`packages-config.nix`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/packages-config.nix) file.

Closing since there doesn't seem to be anything to be done on the nixos-search side.
