### ISSUE TITLE
Exact matches not showing up first

### ISSUE THREAD

**Issue by augyg** [NixOS/nixos-search#583]
In searching for numpy, I noticed that the numpy package is listed way down the page and have seen this for other python packages I've looked for recently like matplotlib. 

![image](https://user-images.githubusercontent.com/36346907/208352229-2a16732f-c736-49f7-97f8-99bf7b3dab74.png)

I believe the numpy package or an exact match of the search query should be the "Best Match" as the filter indicates

**Comment by ncfavier** [comment]
This seems to be a regression caused by https://github.com/NixOS/nixos-search/pull/579, since the version [before that](https://github.com/NixOS/nixos-search/pull/559#issuecomment-1302823951) doesn't have that problem :weary: 

I'll try to get it working with [`word_delimiter`](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/analysis-word-delimiter-graph-tokenfilter.html), otherwise I suppose we should revert that PR for now since it didn't solve any real issue.
