### ISSUE TITLE
Scala 3 not found under name `scala_3`

### ISSUE THREAD

**Issue by Garmelon** [NixOS/nixos-search#680]
In PR https://github.com/NixOS/nixpkgs/pull/171641, `dotty` was renamed to `scala_3` with the name `dotty` remaining available for backwards compatibility. However, on search.nixos.org a search for `scala_3` finds no packages and the package is still called `dotty`.

**Comment by ncfavier** [comment]
The deprecated alias should have been added to `pkgs/top-level/aliases.nix` so that it's not indexed by nixos-search.

There is a [known bug](https://github.com/NixOS/nixos-search/issues/345#issuecomment-1079286996) where nix-env discards duplicate attributes based on pointer equality, which is the case here between `pkgs.scala_3` and `pkgs.dotty`, so Nix just picks one of them (in this case dotty). Anyway, this should be fixed in nixpkgs.
