### ISSUE TITLE
[review] Loss of search-as-you-type is a major loss of functionality

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-search#71]
*As part of the review for https://github.com/NixOS/nixos-homepage/pull/454*

* * *

This is **especially** for the options, as it affects packages a bit less.

I'm bad at remembering things. All things. I generally don't remember the option names right, but only parts of them. I actually **use** the search-as-you-type feature of the site to work around my failings.

Losing search as you type in options would actively harm, at the very least, **my** ability to give help regarding options, in addition to slow down considerably my own personal use of options.

If this is not possible, I will likely have to implement an additional, web-based or not, fuzzy-finder that searches as you type for option names.

**Comment by garbas** [comment]
This was a known loss from the beginning since we are using elasticsearch on the backend and not loading all the data in the browser.

I personally was actually annoyed by search-as-you-type (and also [some others](https://github.com/NixOS/nixos-homepage/issues/322) as well), but i understand that it is useful to others.

Plan is to bring some sort of search as you type functionality via [Completion suggester](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html#completion-suggester) which I think will address your use case.

If you agree with the above proposal I would close this ticket since the work on completion suggesters is being tracked under #34

**Comment by samueldr** [comment]
The linked issue is finding it problematic *because of the performance issues*. It is unclear whether it would be undesirable if there was not the performance issues of the package set being handled in the browser.

I am 99.99% sure I am not alone that will find, mainly for the options, that the loss of search as you type fuzzy finding is a net regression in usability for the search. You don't have to block on my opinion, but I am saying it, it's not going to be liked.

At the very least, I now know I have to play around finding a useful replacement.

**Comment by samueldr** [comment]
Reading from the elastic.co link you shared, there is a link to [Search-as-you-type datatype](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-as-you-type.html).

I'm not experienced with this all, but doesn't that sound exactly like what is needed?

**Comment by adisbladis** [comment]
This is being addressed in https://github.com/NixOS/nixos-search/pull/74

**Comment by lheckemann** [comment]
First of all: great job on this new search tool, it's wonderfully speedy.

That said, this completion UI strikes me as counterproductive (these observations are based entirely on using it, I haven't looked at the code):
- It's slower than the actual search (!?): if I type "sound" and press enter, I'll get the "real" search results before the completions show, while the completion seems to be slow enough to warrant a loading animation
- It doesn't add any value — It shows fewer relevant options, since it's only based on option name prefixes
- It hides other UI behind a popup that contains little information
- It adds a level of indirection before the relevant information: I have to select an option from the dropdown, _then_ click on the option name again in the real results, in order to see the option's documentation. In detail, considering a "happy path" where the desired result is available on the first page of results:
  1. Type search term, e.g. "sound"
  2. Select result from dropdown, e.g. "sound.mediaKeys"
  3. Click outside dropdown to dismiss it
  4. Click on option (e.g. "sound.mediaKeys.enable") to see docs

  Without the dropdown on the new interface, it's better (though this is discouraged by the loading animation for the suggestions):
  1. Type search term, e.g. "sound"
  2. Press enter
  3. Click on option to see docs

  Whereas with the old search, it's better still (not sure what this "reloading" behaviour is?):
  1. Type search term, e.g. "sound"
  2. Click on option to see docs

Video of the first approach vs the old search: https://sphalerite.org/dump/optionsearch.mp4

**Comment by garbas** [comment]
@lheckemann option (b) is not possible to do since the whole thing will become too expensive on the backend. suggestions queries are much simpler queries we do to the backend. But we could of course try.

I'm currently working on last issue regarding suggestions (#120). 

If you are interested I would love to have a screen sharing session with you to learn more how you think UX should be, since we all come with some assumptions that are impossible to write in text.

**Comment by garbas** [comment]
I will actually close this issue since it was already implemented and there is already a ticket for further improvements.
