### ISSUE TITLE
Use / to search

### ISSUE THREAD

**Issue by dev-ardi** [NixOS/nixos-search#762]
https://github.com/NixOS/nixos-homepage/issues/1382

I don't want to have to use my mouse to select the search box!
This is mainly for https://search.nixos.org/ but it could also be applied to the wiki and other places.

In most places you can use / to search. Github, gitlab, google search, rustdoc (soon)... It's the default vi key for search so I suggest using that.

**Comment by thecijal** [comment]
It would be pretty cool to get into the search box by typing `/`. I also think `<Ctrl>`+`<K>` would be awesome.

**Comment by dev-ardi** [comment]
> It would be pretty cool to get into the search box by typing `/`. I also think `<Ctrl>`+`<K>` would be awesome.

Once you have support for once it's probably trivial to add it for another hotkey. Curious, why <kbd>Ctrl</kbd>+<kbd>k</kbd>?

**Comment by thecijal** [comment]
Because `Ctrl`+`k` is a very common one as well as `/`.
Just a few examples:

- https://hub.docker.com/
- https://piped.video/
- https://laravel.com/docs/11.x
- https://svelte.dev/
- https://react.dev/
- https://vuejs.org/
- https://vuetifyjs.com/en/
- https://tailwindcss.com/
- https://getbootstrap.com/
- Thunderbird (version 8 and later): Search All Messages (Global Search)
