### ISSUE TITLE
versions in web view does not correspond to available packages.

### ISSUE THREAD

**Issue by Spatenheinz** [NixOS/nixos-search#768]
I found a problem that seem rather strange to me.
Searching for clang-tools_17 in 23.11, gives me this:
https://search.nixos.org/packages?channel=23.11&from=0&size=50&sort=relevance&type=packages&query=clang-tools_17
This heavily suggest to me that clang-tools v.17 should be available from 23.11, however it is not part of nixpkgs per commit 057f9ae (i.e. tag 23.11).
Either I dont understand what nixos-search points to or there is something wrong with the commit that is being queried.

Can you help me figure this out?

**Comment by wegank** [comment]
`clang-tools_17` is a package that has been backported to the [release-23.11 branch](https://github.com/NixOS/nixpkgs/tree/release-23.11). The 23.11 tag only corresponds to a commit from last November marking the NixOS 23.11 release, and is not suitable for daily use due to the lack of backports and security fixes.

**Comment by Spatenheinz** [comment]
Ah i see. I should use nixos-23.11, when fetching tarball instead.
Sorry for my confusion.
