### ISSUE TITLE
Show channels as buttons (like before) and not in dropdown

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-search#92]
I don't like hiding information behind a drop down.

Can we have a channel list like ubuntu, like i suggested here?
https://github.com/NixOS/nixos-homepage/pull/209#issuecomment-379875644

![38519355-e35d38b2-3c3f-11e8-87b5-f1167eb05807](https://user-images.githubusercontent.com/91113/84422743-c22d5000-ac1d-11ea-8abd-f57bc488a6a5.png)

**Comment by samueldr** [comment]
I didn't end up mentioning it in the review as I refrained from unnecessary bike shedding, but I agree. 

Here's another implementation example:

![image](https://user-images.githubusercontent.com/132835/84445388-e2efa880-ac11-11ea-9d0e-fea00f1e77f9.png)

**Comment by garbas** [comment]
:+1: I'm going to change it to what it was before, since I plan to only index 3 channels at all times. And I want to reach current goal (the same functionality as existing search) as soon as possible. 

But I think we need add much more search options and before doing any change I would like to collect ideas which options we need to fit next to search input. For this I opened a separate issue (#95) and lets discuss the different search options there.

**Comment by garbas** [comment]
I'm going to hijack this ticket and turn it into a proposal that search input looks like in current packages/options search.
