### ISSUE TITLE
[review] Large result sets pagination trouble

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-search#94]
*As part of the review for https://github.com/NixOS/nixos-homepage/pull/454*

* * *

I am unsure what is going on, but bear with what I am observing:

https://search.nixos.org/packages?query=haskell&from=0&size=15&channel=unstable

 * Search for `haskell`
 * Observe results are an oddly round *0-15 of 10000*.
 * Try to access last page
 * Observe  
   ![image](https://user-images.githubusercontent.com/132835/84446707-20edcc00-ac14-11ea-8f2d-1bc8120ac08f.png)
 * Observe URL referencing `&from=9990`

I guess the app will need to *somehow* act in a less error-y way for these cases. First off, I'd say that if the size can be understood as *indefinite*, we should show *of too many results* or something like that. Then, disable the "Last" page navigation, and when going over the limit (is it detectable?) drop them into a page saying they should search with more precise terms, or something of the like.

**Comment by garbas** [comment]
There is a limit in elasticsearch that sets this limit to 10000 to have the search perform efficiently. Now we could [raise this limit](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html) or switch to [scroll api](https://www.elastic.co/guide/en/elasticsearch/reference/7.4/search-request-body.html#request-body-search-scroll), but I'm not sure either of this two solutions would improve the usability of the search.

The primary purpose when you are searching for:
1. a package is that you are looking for *one* package that you want to install or just see if it exists in nixpkgs.
2. an option is that you are looking for a list of possible sub-options that lets you configure a nixos module.

Both of the above use cases make sense if they are performant and show relevant results at the top. You might need to click few times next to look at different pagination pages, but I don't see a use case where one would be clicking Next link 100 times.

I think you already hinted that we might want to actually show things differently when we hit 10000 results.

I would propose we do two things, when we reach 10000 result items:
1. show that there is more then 10000 by adding `+`. example: `Showing results 0-15 of +10000. Try to do a better search query to view more relevant search results.` (I'm not sure about the text, but I think we can write something there that you should do a better search with less results receive more relevant results).
2. Hide "Last" button/link since it makes no sense in this case.

@samueldr what do you think?

**Comment by garbas** [comment]
Also I will need to make sure `size` of the result page is reduces, when doing query when `from + size` is more then 10000. This is to avoid 404.

**Comment by garbas** [comment]
@samueldr I went ahead and already implemented in #99. Give it a look.
