### ISSUE TITLE
Search input, channels and other search options

### ISSUE THREAD

**Issue by garbas** [NixOS/nixos-search#95]
Currently a user needs to:
1. Select if they want to search packages or options
2. Select the channel (or just leave the default)
3. Input their query

But going forward I would like to simplify even more how a user searches and add much more search options. Doing this blindly and just adding check boxes will lead to a poor design. And this is the reason for this issue, to collect all ideas, search options and looking into future how to design best user experience.

Things to consider in out discussion:

- "Show unfree packages" checkbox option
- "Show broken packages" checkbox option
- "Licences" multi select option
- "Maintainers" multi select option
- "Package sets" multi select option (pythonPackages, haskellPackages, rPackages, ...)
- Do different types of sorting make sense? Alphabetically? or is relevance search the only one we actually care
- To not "scare" the user we can only show only few options next to search input and once search happens we can show the rest of the options hidden behind the "Advance search options..." link.
- Can we make only one search which yield results for for different types: Packages, Options, Issues, Documentation, ...  We could again do something similar as google does it, where you can see tabs of different type of results *after* you made the search, eg: All, Images, Maps, News, ...

**Comment by turboMaCk** [comment]
I think it might be a good idea talk about this before the redesign. I think the idea is great. The only point I'm a bit afraid is selection of maintainer which might be quite tricky ux-wise provided how many there are and how much this can grow in the future. I would probably suggest de-scoping it from first iteration on this. I'm not sure about priority of including issues and documentation in first iteration as well since these also can be extracted as separate epic imo.

**Comment by garbas** [comment]
@turboMaCk if you have time come to `#nixos-marketing` channel and we can have scope this correctly.

**Comment by turboMaCk** [comment]
resolved by https://github.com/NixOS/nixos-search/pull/261
